- name: Astra test project
  hosts: all
  become: yes
  tasks:
    - name: install modules # установка необходимых пакетов
      apt:
        pkg:
          - docker
          - docker-compose
          - prometheus-node-exporter
    - name: start docker containers
      community.docker.docker_compose:
        project_name: docker
        definition:
          version: "3.7"
          networks:
            local:
              driver: bridge # настройка сетевого адаптера для контейнеров
          services:
            prometheus:                 
              build:
                context: /tmp/prometheus # директория для Dokerfile, переданная в Vagrantfile
                dockerfile: Dockerfile
              container_name: prometheus
              hostname: prom
              networks: 
                - local
              ports:
                - "9090:9090" # прокинуть порт для Prometheus
            grafana: 
              image: "grafana/grafana:latest"
              container_name: grafana
              hostname: graf
              networks: 
                - local
              ports:
                - "3000:3000" # прокинуть порт для web Grafana
              volumes:
                - /tmp/grafana:/etc/grafana/provisioning # директория для настроек Grafana, переданная в Vagrantfile