apiVersion: 1
# Загрузка данных из Prometheus
datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prom:9090 # адрес Prometheus 
  jsonData:
    graphiteVersion: "1.1"
    tlsAuth: false
    tlsAuthWithCACert: false
  version: 1